---
- name: Services check
  hosts: AlmaLinux
  become: yes
  tasks:
    - name: Check if services are running, if not, the playbook starts the service
      ansible.builtin.systemd_service:
        name: "{{ item }}"
        state: started
      with_items:
        - httpd.service
        - mysqld.service
        - php-fpm.service

    - name: Check if services are running
      command: systemctl status "{{ item }}"
      with_items:
        - httpd.service
        - mysqld.service
        - php-fpm.service
      register: services_state

    - name: Check if containers are on the system.
      docker_container_info:
        name: "{{ item }}"
      register: container_status
      loop:
        - mariadbalma
        - almaweb
        - watchtower

    - name: Display container status
      debug:
      loop: "{{ container_status.results }}"