---
- name: Authenticate to Azure using device code and create Azure snapshots
  hosts: localhost
  gather_facts: false  # Keep gathering facts disabled

  tasks:

    - name: Get current date in YYYY-MM-DD format using shell command
      shell:
        cmd: date +%Y-%m-%d
        executable: /bin/bash
      register: current_date_shell

    - name: Create Azure snapshots for multiple disks
      azure_rm_snapshot:
        resource_group: LAB-ANDREGALVAO
        name: "alma9-patchTuesday-{{ current_date_shell.stdout }}"
        location: northeurope
        tenant: Syone
        subscription_id: "92a32112-068b-4767-9112-8c18589c1909"
        creation_data:
          create_option: Copy
          source_id: '/subscriptions/92a32112-068b-4767-9112-8c18589c1909/resourceGroups/LAB-ANDREGALVAO/providers/Microsoft.Compute/disks/alma9docker_OsDisk_1_2962922a222149b5bef9a254f9c065f7'

    - name: Create snapshot for debian12ansible disk
      azure_rm_snapshot:
        resource_group: LAB-ANDREGALVAO
        name: "debian12-patchTuesday-{{ current_date_shell.stdout }}"
        location: northeurope
        tenant: Syone
        subscription_id: "92a32112-068b-4767-9112-8c18589c1909"
        creation_data:
          create_option: Copy
          source_id: '/subscriptions/92a32112-068b-4767-9112-8c18589c1909/resourceGroups/LAB-ANDREGALVAO/providers/Microsoft.Compute/disks/debian12ansible_OsDisk_1_e2114c7c4bb44dfd9272a91870951e74'
