---
- name: Remover chaves e adicionar novas
  hosts: all
  become: yes
  tasks:
  - name: Remover chave autorizada antiga
    ansible.posix.authorized_key:
      user: marcodomingos
      state: absent
      key: "{{ lookup('file', '/home/marcodomingos/.ssh/id_ed25519.pub') }}"

  - name: Adicionar nova chave autorizada
    ansible.posix.authorized_key:
      user: marcodomingos
      state: present
      key: "{{ lookup('file', '/home/marcodomingos/.ssh/ansiblekey.pub') }}"
