---
- name: Deploy Wordpress
  hosts: UbuntuServer
  become: yes
  vars:
   wordpressconf: /home/marcodomingos/wordpressUbuntu.conf
   sitesavailable: /etc/apache2/sites-available/wordpress.conf

  tasks:
    - name: Updates Ubuntu before Wordpress instalation
      ansible.builtin.package:
        name: "*"
        state: latest

    - name: Install dependencies for Wordpress
      ansible.builtin.apt:
        name:
          - apache2 
          - ghostscript 
          - libapache2-mod-php 
          - mysql-server 
          - php 
          - php-bcmath 
          - php-curl 
          - php-imagick 
          - php-intl 
          - php-json 
          - php-mbstring 
          - php-mysql 
          - php-xml 
          - php-zip

    - name: Creates a folder called www in srv
      ansible.builtin.shell:
        cmd: mkdir -p /srv/www

    - name: Changes the owner and group owner of the folder www
      ansible.builtin.shell:
        cmd: chown www-data:www-data /srv/www

    - name: Downloads wordpress, extracts the content into /srv/www and changes all files owner to www-data
      ansible.builtin.shell:
        cmd: curl https://wordpress.org/latest.tar.gz | sudo -u www-data tar zx -C /srv/www

    - name: Copy wordpress.conf to the directory /etc/apache2/sites-available/ from my homefolder
      ansible.builtin.copy:
        src: "{{ wordpressconf }}"
        dest: "{{ sitesavailable }}"

    - name: Enable wordpress site
      ansible.builtin.command:
        chdir: /etc/apache2/sites-available/
        cmd: a2ensite wordpress

    - name: Enable rewrite module
      ansible.builtin.command:
        chdir: /etc/apache2/sites-available/
        cmd: a2enmod rewrite

    - name: Disable the default site 
      ansible.builtin.command:
        chdir: /etc/apache2/sites-available/
        cmd: a2dissite 000-default

    - name: Reload apache2.service
      ansible.builtin.systemd_service:
        name: apache2
        state: reloaded
        
    - name: Create database for wordpress with the name wordpress
      mysql_db:
        name: wordpress
        login_user: root
        login_password: 27Sy72
        encoding: utf8
        state: present

    - name: Creates the user wordpress and grants all privileges to this user on wordpress database
      mysql_user:
        login_user: root
        login_password: 27Sy72
        name: wordpress
        password: 27Sy72
        priv: 'wordpress.*:ALL,GRANT'
        state: present

    - name: Connect database to wordpress
      ansible.builtin.command:
        cmd: sudo -u www-data cp /srv/www/wordpress/wp-config-sample.php /srv/www/wordpress/wp-config.php

    - name: Sets the database into the configuration file
      ansible.builtin.command:
        cmd: sudo -u www-data sed -i 's/database_name_here/wordpress/' /srv/www/wordpress/wp-config.php

    - name: Sets the username of wordpress database into the configuration file
      ansible.builtin.command:
        cmd: sudo -u www-data sed -i 's/username_here/wordpress/' /srv/www/wordpress/wp-config.php

    - name: Sets the user password of wordpress database into the configuration file
      ansible.builtin.command:
        cmd: sudo -u www-data sed -i 's/password_here/27Sy72/' /srv/www/wordpress/wp-config.php
